language: node_js
node_js:
- '6'
deploy:
  provider: heroku
  api_key:
    secure: mlJCFA5IQLpwoxgbjaV/RCIdqqX955pyV7YDijGGIyO2bYVfPMq3XbrQgziqL/9ngNcHgaYeM98ITTjAEsVoS37joRc1is0bVEo162L2GamxuwZv402zgtyAgGqRf11dDKuNwFyMhIe5KZBTLbHwzIp0rKLZPGTVnqh14zxr69VPETnQRyJrpSB/FdElkQTJQohHfqjpIFfb9msj2mvP7Wx4zIQiWQpzHJbv9z4r3VRZH28qjyJHS25ienvRbYMqHxc6fX57L/b8DeAbuzlTPsKGNE0tahKYkR/rNTvZBSbwyDkrgEF+juywt1niPEW0fWGjiLL4c4F7aTbTS1amuUUxSDBwHV3a3JNySFLMq5dyVE7TRtNnqoVQ5hEHuzpLMrZPpgYwSpbU133um10SLwy8Hl5x+ERj+5I/z3J8E+VVQQqSP4n7xnvFUVCwtxvMhLxNU25iD6wMl5jXDMNHFIjvDCsMJgVuMWlJnvq9bfadotctPF58IlmilJeERIARq/cTI4ESdUtEhktxOwAb79KJLgHsjLtK9Iy520jWAaXLK6gFit5Z37pJA9R0KyhuEhOEBstzd5ZxIHgr3SgGgj1QsRjYpU0OdYWqS7453OoxgIgqHg39JWuVn8Eqd6mgWebPBirYSdQyZ3wL9DvTbHJB2eX0ZXfeXl3Xq7fd5WA=
  app: zhe-hacker-news
